---
title: "Model Fitting and selection"
author: "Shan"
date: "05/02/2019"
output:   
  pdf_document:
         latex_engine: xelatex
fontsize: 12pt
geometry: margin=1.1in 

---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(tableone)
library(lavaan)
library(expss)
library(mirt)
```

## Import data 
```{r}
## read in data cleaned 
scale_raw = read.csv(file = "./index.csv", head = TRUE, sep = ",")
head(scale_raw)
```
 
```{r}
## scale_raw to index data：add one row for score. 
scale_df = scale_raw %>% 
   dplyr::select(rnid, EB2a, CEP1, HEC1r1b,HEC3r3e,HEC6a,
         EB7a, HEC3r3f) %>% 
   mutate(sum_score = rowSums(dplyr::select(., -rnid)))
```

```{r}
## Distribution of the sum scores 
ggplot(scale_df, aes( sum_score)) +
  geom_bar()

```

```{r}
## Demographical  variables  
append = readxl::read_xlsx("./data_append.xlsx") %>% 
  mutate(rnid = RNID)

## Combine the cleaned dataset with appendix.
full_data = merge(append, scale_df, by = "rnid" )
write.csv(full_data, "./full.csv")
```

## Table one 

1. Recode Age into groups 
```{r}
agebreaks <- c(0,1,5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,500)
agelabels <- c("0-1","1-4","5-9","10-14","15-19","20-24","25-29","30-34",
               "35-39","40-44","45-49","50-54","55-59","60-64","65-69",
               "70-74","75-79","80-84","85+")

full_data = full_data %>% 
  mutate(agegroups =  cut(Age, 
                  breaks = agebreaks, 
                  right = FALSE, 
                  labels = agelabels)) 
```

2. Education
```{r}
full_data = full_data %>% 
  mutate(Education = fct_recode(Education, 
                                "Low" = "Prefer not to answer", ## remove the levels
        "Low" = "Incomplete Secondary (high school) Education", 
        "Low" =  "Secondary (high school) Education",
         "Medium" = "Vocational or Technical Degree",
         "Medium" = "Some College, University, Technical School or Further Education" , 
        "Medium" = "Associate's Degree",
         "High" = "Bachelor's Degree", 
        "High" = "Master's Degree", 
         "High" = "Doctoral or Professional Degree (PhD, Ed.D, JD, DVM, DO, MD, DDS, or similar)")
        ) 

```

3. Income and employment
```{r}
energy.new = full_data %>%
  filter(Race != "Other") %>% 
  filter(Race != "Prefer not to answer") %>% 
  filter(Race != "DO NOT USE") %>% 
  filter(`Hispanic Origin` != "Prefer Not to Answer") %>% 
  filter(Children != "Prefer not to state") %>% 
  filter(Education != "Prefer not to answer") %>% 
  filter(`Household Income` != "Prefer not to answer") %>%  
  filter(`Household Income` !=  "None of the above") %>% 
  filter(`Employment Status` != "None of the above") %>% 
  mutate(Hispanic = factor(`Hispanic Origin`, levels = c("No","Yes") ),
         `Household Income` = factor(`Household Income`, 
  levels = c("< 15,000","15,000 to 24,999", "25,000 to 49,999", "50,000 to 74,999","75,000 to 99,999", "100,000 to 149,999" , "150,000 to 199,999", "200,000 to 249,999", "250,000 to 499,999", "500,000 to 999,999","1 million +" ))) %>% 
  janitor::clean_names()

```


### Table 1: Descriptive social demographical 

(1) Table 1 

```{r}

# Create a variable list which we want in Table 1:"No.in household", "Household Income", "Employment Status","Home Ownership"

listVar <- c("region", "race", "education",
             "children", "gender", "agegroups",
              "number_in_household", "sum_score",
             "household_income", "employment_status", "home_ownership" )

# Define categorical variables
catVar <- c("region", "race",   "education",
             "children", "gender","agegroups", 
             "number_in_household", "sum_score",
             "household_income", "employment_status", "home_ownership")

# Total Population
table1 <- CreateTableOne(vars = listVar, data = energy.new, 
                         strata = c("hispanic"),
                         factorVars = catVar,
                         includeNA = FALSE
                   )
print(table1, quote = TRUE, test = TRUE )

```


```{r}
listVar <- c("region", "race", "hispanic",  "education",
             "children", "gender", "agegroups",
              "sum_score",
             "household_income", "employment_status", "home_ownership" )

# Define categorical variables
catVar <- c("region", "race", "hispanic",  "education",
             "children", "gender","agegroups", 
             "sum_score",
             "household_income", "employment_status", "home_ownership")

# Total Population
table1 <- CreateTableOne(vars = listVar, data = energy.new, 
                         strata = c( "number_in_household"),
                         factorVars = catVar,
                         includeNA = FALSE
                   )
print(table1, quote = TRUE, test = TRUE )
```


## Model construction: regression with the health status covariates 

```{r}

```



